#!/usr/bin/env sh
X="$(xrandr | grep '*' | uniq | awk '{print$1}' | cut -d 'x' -f1)"  # your horizontal screen resolution
Y="$(xrandr | grep '*' | uniq | awk '{print$1}' | cut -d 'x' -f2)"  # your vertical screen resolution
XP="$(xdotool getmouselocation | awk '{print$1}' | sed 's/x://g')" #mouse coordinate X
YP="$(xdotool getmouselocation | awk '{print$2}' | sed 's/y://g')" #mouse coordinate Y

bar_length=62 # % length w.r.t X width; edit to suit your need
w=$(($X*$bar_length/100)) # bar length; % width as per panel_length
x=$(($X*327/1000)) # 27% offset of X resolution


# BOTTOM BAR
 y=$(($Y*997/1000)) # y offset from y resolution; current is 99.7% of Y resolution

# TOP BAR ; comment out above line and uncomment below line for TOP BAR
# y=$(($Y-$Y))  # y offser from y resolution; current is 0.3% of Y resolution;

## right for systray ; add your tray app [stalonetray OR trayer; below is trayer command]
# dwm is patched to show systray so no need of trayer

## pkill dzen2 and conky instances first
killall dzen2 conky &
sleep 5 && conky -c ~/dwm-6.4/dwm-dzen-unifiedConky | dzen2 -p -e 'enterslave=grabkeys;leaveslave=ungrabkeys; button4=scrollup;button5=scrolldown; key_Left=scrollup;key_Right=scrolldown; button1=menuexec' -h '18' -w $w -ta l -x $x -y $y -fn 'FiraCode Nerd Font:pixelsize=10:antialias=true' &

# optional transparency
sleep 10 && exec `(transset .9 -n "dzen title" >/dev/null 2>&1 &)` &

## deps for  forecast
location="MY_CITY" ## TYPE YOUR CITY NAME WITHIN QUOTES
while : ;do curl -s 'http://v1.wttr.in/$location\?MT' | tail -n33 | head -n30 > /tmp/asciiwttr;sleep 1801;done
